[project]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "mojomq"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = "~=25.3"
python = "==3.12"
numpy = "<2.0"
